services:
  top-shelf:
    image: thefilthycount/top-shelf:latest
    container_name: top-shelf
    restart: unless-stopped
    ports:
      - "8891:8891"
    volumes:
      - /volume4/docker/top-shelf:/app/data
      - /volume4/docker/top-shelf/static:/app/static
      - /volume3/Top-Shelf:/library
      - /volume4/Downloads:/downloads
    environment:
      - TZ=Europe/London
